layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: mentordeprogramacion
  # telegram: your_username
  twitter: Mdeprogramacion
  # unsplash: your_username
  # vk: your_username
  website: https://www.youtube.com/channel/UCTwhsU_rVod3JpdV2durdDg
  # youtube: mentordeprogramacion

theme: jekyll-theme-minimal
